"""new field in user model (joined)

Revision ID: 6ac9ce09ea02
Revises: 619736f59424
Create Date: 2018-05-01 15:45:37.041724

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ac9ce09ea02'
down_revision = '619736f59424'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('joined', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_user_joined'), 'user', ['joined'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_joined'), table_name='user')
    op.drop_column('user', 'joined')
    # ### end Alembic commands ###
