"""new field in post (score)

Revision ID: a20a61a7dc28
Revises: 6ac9ce09ea02
Create Date: 2018-05-01 16:01:32.870602

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a20a61a7dc28'
down_revision = '6ac9ce09ea02'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('score', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_post_score'), 'post', ['score'], unique=False)
    op.drop_index('ix_user_joined', table_name='user')
    op.drop_column('user', 'joined')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('joined', sa.DATETIME(), nullable=True))
    op.create_index('ix_user_joined', 'user', ['joined'], unique=False)
    op.drop_index(op.f('ix_post_score'), table_name='post')
    op.drop_column('post', 'score')
    # ### end Alembic commands ###
